#!/bin/bash
INPUT=$1

if [[ -z $INPUT ]]; then
  INPUT="wwwroot"
  printf "Directory option not set, installing into ./$INPUT/...\n"
else
  printf "Installing in to ./$INPUT/...\n"
fi

# Select a version
printf "\nWhich ProcessWire branch do you want to install?\n"
options=("master" "dev")
select BRANCH in "${options[@]}"; do test -n "$BRANCH" && break; echo ">>> Invalid selection, please try again"; done

printf "\nDownloading ProcessWire $BRANCH branch, please hold on...\n"

# Get ProcessWire master and prepare files
if [ "$BRANCH" == "master" ]; then
  curl -o processwire.zip https://github.com/ryancramerdesign/ProcessWire/archive/master.zip -# -L
fi

if [ "$BRANCH" == "dev" ]; then
  curl -o processwire.zip https://github.com/ryancramerdesign/ProcessWire/archive/dev.zip -# -L
fi

unzip -q processwire.zip
rm processwire.zip

if [ "$BRANCH" == "master" ]; then
  mv ProcessWire-master $INPUT
fi

if [ "$BRANCH" == "dev" ]; then
  mv ProcessWire-dev $INPUT
fi

chmod -R u+rwX,go+rX,go-w $INPUT
mv $INPUT/htaccess.txt $INPUT/.htaccess

cd $INPUT

# Prompt for site profile
printf "\nWhich site profile will you be using?\n"
select d in site-*/; do test -n "$d" && break; echo ">>> Invalid selection, please try again"; done
mv $d site/
rm -rf site-*/

# Set permissions
chmod 777 site/assets
chmod 777 site/modules
chmod 666 site/config.php

printf "\n"
read -p "Press [Enter] once you've finished the installation process to remove the install files..."
rm install.php
rm -rf site/install
printf "\nInstallation files removed.\n"

printf "\nDirectory \"$INPUT\" all set for ProcessWire. Have fun! \n"
